### ISSUE TITLE
Chrome DevTools support

### ISSUE THREAD

**Issue by uebayasi** [dillonkearns/elm-electron-starter#1]
It would be nice if this template is ready to be used from DevTools.  If I open DevTools, `Sources' shows only `index.html'.  I suppose, by using Source Maps, *.elm files and corresponding *.js files are recognized by DevTools.

**Comment by uebayasi** [comment]
Ignore this.  I was only ignorant about how DevTools works.  I do see it can open app.js (made from App.elm) via Cmd+P.

**Comment by dillonkearns** [comment]
Sounds good, let me know if you have any other feedback!
